apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: cron-tap-covid
  namespace: argo
spec:
  schedule: "0 0/4 * * *"
  workflowSpec:
    serviceAccountName: workflow
    entrypoint: tap-runner

    templates:
    - name: tap-runner
      steps:
      - - name: tap-to-target
          arguments:
            parameters:
            - name: tap_name
              value: tap-covid-19
            - name: tap_image
              value: tap-covid-19
            - name: tap_image_tag
              value: latest
            - name: target_schema
              value: covid
          templateRef:
            name: singer-workflow
            template: tap-to-target
