# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: artifact-repositories
data:
  minio: |
    s3:
      bucket: artifacts
      endpoint: minio:9000
      insecure: true
      accessKeySecret:
        name: artifact-credentials
        key: accesskey
      secretKeySecret:
        name: artifact-credentials
        key: secretkey
