apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: singer-workflow
  namespace: argo
spec:
  entrypoint: tap-to-target

  templates:
  - name: tap-to-target
    inputs:
      parameters:
      - name: tap_image
      - name: target_image
      - name: tap_image_repo
        value: stkbailey
      - name: target_image_repo
        value: stkbailey
      - name: tap_image_tag
        value: latest
      - name: target_image_tag
        value: latest
      - name: artifact_bucket
        value: argo-artifacts-local
    steps:
    - - name: tap
        template: singer-tap
        arguments:
          parameters:
          - name: tap_image
            value: "{{inputs.parameters.tap_image}}"
          - name: tap_image_tag
            value: "{{inputs.parameters.tap_image_tag}}"
          - name: tap_image_repo
            value: "{{inputs.parameters.tap_image_repo}}"
          - name: artifact_bucket
            value: "{{inputs.parameters.artifact_bucket}}"
    - - name: target
        template: singer-target
        arguments:
          parameters:
          - name: tap_image
            value: "{{inputs.parameters.tap_image}}"
          - name: target_image
            value: "{{inputs.parameters.target_image}}"
          - name: target_image_tag
            value: "{{inputs.parameters.target_image_tag}}"
          - name: target_image_repo
            value: "{{inputs.parameters.target_image_repo}}"
          - name: artifact_bucket
            value: "{{inputs.parameters.artifact_bucket}}"
          artifacts:
          - name: tap-output
            from: "{{steps.tap.outputs.artifacts.tap-output}}"

  - name: singer-tap
    container:
      image: "{{inputs.parameters.tap_image_repo}}/{{inputs.parameters.tap_image}}:{{inputs.parameters.tap_image_tag}}"
    inputs:
      parameters:
      - name: tap_image
      - name: tap_image_tag
      - name: tap_image_repo
      - name: artifact_bucket
      artifacts:
      - name: tap-config
        path: /tmp/config.json
        s3:
          bucket: "{{inputs.parameters.artifact_bucket}}"
          key: "singer-configs/{{inputs.parameters.tap_image}}/config.json"
          endpoint: my-minio-endpoint.default:9000
          accessKeySecret:
            name: artifact-credentials
            key: accessKey
          secretKeySecret:
            name: artifact-credentials
            key: secretKey
      - name: tap-catalog
        path: /tmp/catalog.json
        s3:
          bucket: "{{inputs.parameters.artifact_bucket}}"
          key: "singer-configs/{{inputs.parameters.tap_image}}/catalog.json"
          endpoint: my-minio-endpoint.default:9000
          accessKeySecret:
            name: artifact-credentials
            key: accessKey
          secretKeySecret:
            name: artifact-credentials
            key: secretKey
      - name: tap-state
        path: /tmp/state.json
        s3:
          bucket: "{{inputs.parameters.artifact_bucket}}"
          key: "singer-configs/{{inputs.parameters.tap_image}}/state.json"
          endpoint: my-minio-endpoint.default:9000
          accessKeySecret:
            name: artifact-credentials
            key: accessKey
          secretKeySecret:
            name: artifact-credentials
            key: secretKey
    outputs:
      artifacts:
      - name: tap-output
        path: /tmp/tap_output.txt

  - name: singer-target
    container:
      image: "{{inputs.parameters.target_image_repo}}/{{inputs.parameters.target_image}}:{{inputs.parameters.target_image_tag}}"
    inputs:
      parameters:
        - name: tap_image
        - name: target_image
        - name: target_image_tag
        - name: target_image_repo
        - name: artifact_bucket
      artifacts:
      - name: target-config
        path: /tmp/config.json
        s3:
          bucket: "{{inputs.parameters.artifact_bucket}}"
          key: "singer-configs/{{inputs.parameters.target_image}}/config.json"
          endpoint: my-minio-endpoint.default:9000
          accessKeySecret:
            name: s3-artifact-credentials
            key: accessKey
          secretKeySecret:
            name: s3-artifact-credentials
            key: secretKey
      - name: tap-output
        path: /tmp/tap_output.txt
    outputs:
      artifacts:
      - name: target-output
        path: /tmp/target_output.txt
        s3:
          bucket: "{{inputs.parameters.artifact_bucket}}"
          key: "singer-configs/{{inputs.parameters.tap_image}}/state.json"
          endpoint: my-minio-endpoint.default:9000
          accessKeySecret:
            name: s3-artifact-credentials
            key: accessKey
          secretKeySecret:
            name: s3-artifact-credentials
            key: secretKey
